name: run tests
on:
  push:
    branches: '**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pip libraries
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Run unit tests
        run: python test_app.py
        

